version: '3'
services:
  # user-service:
  #   build:
  #     context: ./user-service
  #     dockerfile: dockerfile
  #   ports:
  #     - '3000:3000'
  #   restart: always
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=abc
  #     - POSTGRES_DB=user-service
  #   depends_on:
  #     # - file-service
  #     - postgres
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  # file-service:
  #   build:
  #     context: ./file-service
  #     dockerfile: dockerfile
  #   # ports:
  #   #   - '3001:3001'
  #   restart: always
  #   # depends_on:
  #   #   - user-service
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=user-service